# permissions for end users to view emailsenderconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: emailsenderconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: task-email-sender
    app.kubernetes.io/part-of: task-email-sender
    app.kubernetes.io/managed-by: kustomize
  name: emailsenderconfig-viewer-role
rules:
- apiGroups:
  - mail.email-sender.com
  resources:
  - emailsenderconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mail.email-sender.com
  resources:
  - emailsenderconfigs/status
  verbs:
  - get
